// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AppSettings = { start_with_windows: boolean, minimize_to_tray: boolean, start_minimized: boolean, auto_update: boolean, duration: number, show_player_winrates: boolean, show_replay_info_after_game: boolean, show_session: boolean, show_charts: boolean, hide_nicknames_in_overlay: boolean, account_folder: string, screenshot_folder: string, color_player1: string, color_player2: string, color_amon: string, color_mastery: string, "hotkey_show/hide": string | null, hotkey_show: string | null, hotkey_hide: string | null, hotkey_newer: string | null, hotkey_older: string | null, hotkey_winrates: string | null, enable_logging: boolean, dark_theme: boolean, language: string, monitor: number, performance_show: boolean, performance_hotkey: string | null, performance_processes: Array<string>, performance_geometry?: [number, number, number, number], rng_choices: { [key in string]: boolean }, player_notes: { [key in string]: string }, main_names: Array<string>, detailed_analysis_atstart: boolean, analysis_worker_threads: number, };

export type ConfigChatPayload = { status: string, chat: ReplayChatPayload, };

export type ConfigPayload = { status: string, settings: AppSettings, active_settings: AppSettings, randomizer_catalog: OverlayRandomizerCatalog, monitor_catalog: Array<MonitorOption>, };

export type ConfigPlayersPayload = { status: string, players: Array<PlayerRowPayload>, loading: boolean, };

export type ConfigReplaysPayload = { status: string, replays: Array<GamesRowPayload>, total_replays: number, selected_replay_file: string | null, };

export type ConfigWeekliesPayload = { status: string, weeklies: Array<WeeklyRowPayload>, };

export type EmptyPayload = Record<symbol, never>;

export type GamesRowPayload = { file: string, date: number, map: string, result: string, difficulty: string, p1: string, p2: string, slot1_commander: string, slot2_commander: string, enemy: string, main_commander: string, ally_commander: string, length: number, main_apm: number, ally_apm: number, main_kills: number, ally_kills: number, extension: boolean, brutal_plus: number, weekly: boolean, weekly_name?: string, mutators: Array<UiMutatorRow>, is_mutation: boolean, };

export type LocalizedLabels = { ko: Array<string>, en: Array<string>, };

export type LocalizedText = { ko: string, en: string, };

export type MonitorOption = { index: number, label: string, };

export type OverlayActionResponse = { status: string, result: OverlayActionResult, message: string, randomizer: RandomizerResult | null, };

export type OverlayActionResult = { ok: boolean, path: string | null, };

export type OverlayColorPreviewPayload = { color_player1?: string, color_player2?: string, color_amon?: string, color_mastery?: string, };

export type OverlayIconValue = number | Array<string>;

export type OverlayInitColorsDurationPayload = { colors: [string | null, string | null, string | null, string | null], duration: number, show_charts: boolean, show_session: boolean, hide_nicknames_in_overlay: boolean, session_victory: number, session_defeat: number, language: string, };

export type OverlayLanguagePreviewPayload = { language: string, };

export type OverlayPlayerInfoPayload = { data: { [key in string]: OverlayPlayerInfoRow }, };

export type OverlayPlayerInfoRow = { "kind": "no_games", note?: string, } | { "kind": "stats", wins: number, losses: number, apm: number, commander: string, frequency: number, kills: number, last_seen_relative: string, note?: string, };

export type OverlayRandomizerBrutalPlus = { brutal_plus: number, mutator_points: OverlayRandomizerRange, mutator_count: OverlayRandomizerRange, };

export type OverlayRandomizerCatalog = { prestige_names: { [key in string]: LocalizedLabels }, mutators: Array<OverlayRandomizerMutator>, brutal_plus: Array<OverlayRandomizerBrutalPlus>, };

export type OverlayRandomizerMutator = { id: string, name: LocalizedText, iconName: string, description: LocalizedText, points: number, };

export type OverlayRandomizerRange = { min: number, max: number, };

export type OverlayReplayPayload = { file: string, map_name: string, main: string, ally: string, mainCommander: string, allyCommander: string, mainAPM: number, allyAPM: number, mainkills: number, allykills: number, result: string, difficulty: string, length: number, "B+": number, weekly: boolean, weekly_name?: string, extension: boolean, mainCommanderLevel: number, allyCommanderLevel: number, mainMasteries: Array<number>, allyMasteries: Array<number>, mainUnits: { [key in string]: [number, number, number, number] }, allyUnits: { [key in string]: [number, number, number, number] }, amon_units: { [key in string]: [number, number, number, number] }, mainIcons: { [key in string]: OverlayIconValue }, allyIcons: { [key in string]: OverlayIconValue }, mutators: Array<string>, bonus: Array<number>, bonus_total?: number, player_stats?: { [key in string]: ReplayPlayerSeries }, mainPrestige: string, allyPrestige: string, Victory?: number, Defeat?: number, Commander?: string, Prestige?: string, newReplay?: boolean, fastest?: boolean, comp: string, };

export type OverlayScreenshotRequestPayload = { path: string, };

export type OverlayScreenshotResultPayload = { ok: boolean, path: string, message: string, };

export type PerformanceVisibilityPayload = { visible: boolean, };

export type PlayerRowPayload = { handle: string, player: string, player_names: Array<string>, wins: number, losses: number, winrate: number, apm: number, commander: string, frequency: number, kills: number, last_seen: number, };

export type RandomizerMutatorResult = { id: string, name: LocalizedText, iconName: string, description: LocalizedText, points: number, };

export type RandomizerResult = { kind: string, commander?: string, prestige?: number, mastery_indices?: Array<number | null>, map_race?: string, mutators?: Array<RandomizerMutatorResult>, mutator_total_points?: number, mutator_count?: number, brutal_plus?: number, };

export type ReplayChatMessage = { player: number, text: string, time: number, };

export type ReplayChatPayload = { file: string, date: number, map: string, result: string, slot1_name: string, slot2_name: string, messages: Array<ReplayChatMessage>, };

export type ReplayPlayerSeries = { name: string, army: Array<number>, supply: Array<number>, killed: Array<number>, mining: Array<number>, };

export type StatsActionPayload = { status: string, result: OverlayActionResult, message: string, stats: StatsStatePayload | null, };

export type StatsStatePayload = { ready: boolean, games: number, detailed_parsed_count: number, total_valid_files: number, analysis?: Record<string, any> | null, main_players: Array<string>, main_handles: Array<string>, analysis_running: boolean, analysis_running_mode?: string, simple_analysis_status: string, detailed_analysis_status: string, detailed_analysis_atstart: boolean, prestige_names: Record<string, any>, message: string, scan_progress: Record<string, any>, };

export type UiMutatorRow = { id: string, name: LocalizedText, iconName: string, description: LocalizedText, };

export type WeeklyRowPayload = { mutation: string, nameEn: string, nameKo: string, map: string, mutators: Array<UiMutatorRow>, mutationOrder: number, isCurrent: boolean, nextDurationDays: number, nextDuration: string, difficulty: string, wins: number, losses: number, winrate: number, };
