// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AnalysisCompletedPayload = { mode: string, message: string, };

export type AnalysisStatusPayload = { status: string, ready: boolean, analysis_running: boolean, analysis_running_mode?: string, current_status: string, simple_analysis_status: string, detailed_analysis_status: string, detailed_parsed_count: number, total_valid_files: number, scan_progress: ReplayScanProgressPayload, };

export type AppSettings = { start_with_windows: boolean, minimize_to_tray: boolean, start_minimized: boolean, auto_update: boolean, duration: number, show_player_winrates: boolean, show_replay_info_after_game: boolean, show_session: boolean, show_charts: boolean, hide_nicknames_in_overlay: boolean, account_folder: string, screenshot_folder: string, color_player1: string, color_player2: string, color_amon: string, color_mastery: string, "hotkey_show/hide": string | null, hotkey_show: string | null, hotkey_hide: string | null, hotkey_newer: string | null, hotkey_older: string | null, hotkey_winrates: string | null, enable_logging: boolean, dark_theme: boolean, language: string, monitor: number, performance_show: boolean, performance_hotkey: string | null, performance_processes: Array<string>, performance_geometry?: [number, number, number, number], rng_choices: { [key in string]: boolean }, player_notes: { [key in string]: string }, main_names: Array<string>, detailed_analysis_atstart: boolean, analysis_worker_threads: number, latest_today_win_bonus_time: string | null, first_win_bonus_display_mode: FirstWinBonusDisplayMode, };

export type ConfigChatPayload = { status: string, chat: ReplayChatPayload, };

export type ConfigPayload = { status: string, settings: AppSettings, active_settings: AppSettings, randomizer_catalog: OverlayRandomizerCatalog, monitor_catalog: Array<MonitorOption>, };

export type ConfigPlayersPayload = { status: string, players: Array<PlayerRowPayload>, total_players: number, loading: boolean, };

export type ConfigReplayVisualPayload = { status: string, visual: ReplayVisualPayload, };

export type ConfigReplaysPayload = { status: string, replays: Array<GamesRowPayload>, total_replays: number, selected_replay_file: string | null, };

export type ConfigWeekliesPayload = { status: string, weeklies: Array<WeeklyRowPayload>, };

export type EmptyPayload = Record<symbol, never>;

export type FirstWinBonusDisplayMode = "hidden" | "available_only" | "always";

export type FirstWinBonusTimerPayload = { visible: boolean, available: boolean, seconds_until_available: number, next_available_time?: string, };

export type GamesRowPayload = { file: string, date: number, map: string, result: string, difficulty: string, p1: string, p2: string, slot1_commander: string, slot2_commander: string, enemy: string, main_commander: string, ally_commander: string, length: number, main_apm: number, ally_apm: number, main_kills: number, ally_kills: number, extension: boolean, brutal_plus: number, weekly: boolean, weekly_name?: string, mutators: Array<UiMutatorRow>, is_mutation: boolean, };

export type LocalizedLabels = { ko: Array<string>, en: Array<string>, };

export type LocalizedText = { ko: string, en: string, };

export type MonitorOption = { index: number, label: string, };

export type OverlayActionResponse = { status: string, result: OverlayActionResult, message: string, randomizer: RandomizerResult | null, };

export type OverlayActionResult = { ok: boolean, path: string | null, };

export type OverlayColorPreviewPayload = { color_player1?: string, color_player2?: string, color_amon?: string, color_mastery?: string, };

export type OverlayIconValue = number | Array<string>;

export type OverlayInitColorsDurationPayload = { colors: [string | null, string | null, string | null, string | null], duration: number, show_charts: boolean, show_session: boolean, hide_nicknames_in_overlay: boolean, session_victory: number, session_defeat: number, language: string, prestige_names: { [key in string]: LocalizedLabels }, };

export type OverlayLanguagePreviewPayload = { language: string, };

export type OverlayPlayerStatsPayload = { data: { [key in string]: OverlayPlayerStatsRow }, };

export type OverlayPlayerStatsRow = { "kind": "no_games", note?: string, } | { "kind": "stats", wins: number, losses: number, apm: number, commander: string, frequency: number, kills: number, last_seen_relative: string, note?: string, };

export type OverlayRandomizerBrutalPlus = { brutal_plus: number, mutator_points: OverlayRandomizerRange, mutator_count: OverlayRandomizerRange, };

export type OverlayRandomizerCatalog = { prestige_names: { [key in string]: LocalizedLabels }, mutators: Array<OverlayRandomizerMutator>, brutal_plus: Array<OverlayRandomizerBrutalPlus>, };

export type OverlayRandomizerMutator = { id: string, name: LocalizedText, iconName: string, description: LocalizedText, points: number, };

export type OverlayRandomizerRange = { min: number, max: number, };

export type OverlayReplayPayload = { file: string, map_name: string, main: string, ally: string, mainCommander: string, allyCommander: string, mainAPM: number, allyAPM: number, mainkills: number, allykills: number, result: string, difficulty: string, enemy: string, length: number, "B+": number, weekly: boolean, weekly_name?: string, extension: boolean, mainCommanderLevel: number, allyCommanderLevel: number, mainMasteryLevel: number, allyMasteryLevel: number, mainMasteries: Array<number>, allyMasteries: Array<number>, mainUnits: { [key in string]: [number, number, number, number] }, allyUnits: { [key in string]: [number, number, number, number] }, amon_units: { [key in string]: [number, number, number, number] }, mainIcons: { [key in string]: OverlayIconValue }, allyIcons: { [key in string]: OverlayIconValue }, mutators: Array<string>, bonus: Array<number>, bonus_total?: number, player_stats?: { [key in string]: ReplayPlayerSeries }, mainPlayerStats?: ReplayPlayerSeries, allyPlayerStats?: ReplayPlayerSeries, mainPrestige: string, allyPrestige: string, Victory?: number, Defeat?: number, Commander?: string, Prestige?: string, newReplay?: boolean, fastest?: boolean, comp: string, };

export type OverlayScreenshotRequestPayload = { path: string, };

export type OverlayScreenshotResultPayload = { ok: boolean, path: string, message: string, };

export type PerformanceVisibilityPayload = { visible: boolean, };

export type PlayerRowPayload = { handle: string, player: string, player_names: Array<string>, wins: number, losses: number, winrate: number, apm: number, commander: string, frequency: number, kills: number, last_seen: number, };

export type RandomizerMutatorResult = { id: string, name: LocalizedText, iconName: string, description: LocalizedText, points: number, };

export type RandomizerResult = { "kind": "commander", commander: string, prestige: number, mastery_indices: Array<number | null>, map_race: string, } | { "kind": "mutator", mutators: Array<RandomizerMutatorResult>, mutator_total_points: number, mutator_count: number, brutal_plus?: number, };

export type ReplayChatMessage = { player: number, text: string, time: number, };

export type ReplayChatPayload = { file: string, date: number, map: string, result: string, slot1_name: string, slot2_name: string, messages: Array<ReplayChatMessage>, };

export type ReplayPlayerSeries = { name: string, army: Array<number>, supply: Array<number>, killed: Array<number>, mining: Array<number>, };

export type ReplayScanProgressPayload = { stage: string, status: string, parsing_status: string, total: number, total_replay_files: number, cache_hits: number, files_already_cached: number, to_parse: number, completed: number, newly_parsed: number, newly_parsed_files: number, failed: number, parse_failed_files: number, parse_skipped: number, parse_skipped_files: number, elapsed_ms: number, total_time_taken_ms: number, };

export type ReplayVisualAssault = { id: string, game_loop: number, seconds: number, x: number, y: number, unit_count: number, units: Array<ReplayVisualUnitCount>, };

export type ReplayVisualFrame = { game_loop: number, seconds: number, units: Array<ReplayVisualUnit>, };

export type ReplayVisualOwnerKind = "main" | "ally" | "amon" | "neutral" | "other";

export type ReplayVisualPayload = { file: string, map: string, result: string, duration_seconds: number, map_width: number, map_height: number, players: Array<ReplayVisualPlayer>, frames: Array<ReplayVisualFrame>, assaults: Array<ReplayVisualAssault>, };

export type ReplayVisualPlayer = { player_id: number, label: string, owner_kind: ReplayVisualOwnerKind, color: string, };

export type ReplayVisualUnit = { id: string, unit_type: string, display_name: string, owner_player_id: number, owner_kind: ReplayVisualOwnerKind, group: ReplayVisualUnitGroup, x: number, y: number, radius: number, interpolate_from_previous: boolean, };

export type ReplayVisualUnitCount = { unit_type: string, display_name: string, count: number, };

export type ReplayVisualUnitGroup = "buildings" | "attack_units" | "defense_buildings" | "enemy_assaults";

export type StatsActionPayload = { status: string, result: OverlayActionResult, message: string, stats: StatsStatePayload | null, };

export type StatsAmonUnitRow = { created: number, lost: number, kills: number, KD: number | string, };

export type StatsAnalysisPayload = { MapData: { [key in string]: StatsMapDataRow }, CommanderData: { [key in string]: StatsCommanderDataRow }, AllyCommanderData: { [key in string]: StatsCommanderDataRow }, DifficultyData: { [key in string]: StatsDifficultyDataRow }, RegionData: { [key in string]: StatsRegionDataRow }, PlayerData: { [key in string]: StatsPlayerDataRow }, AmonData: { [key in string]: StatsAmonUnitRow }, UnitData: StatsUnitDataPayload | null, MapDataReady?: boolean, };

export type StatsCommanderDataRow = { Frequency: number, Victory: number, Defeat: number, Winrate: number, MedianAPM: number, KillFraction: number, Mastery: Record<string, number>, MasteryDistribution: Record<string, Record<string, number>>, MasteryDistributionByPrestige: Record<string, Record<string, Record<string, number>>>, Prestige: Record<string, number>, MasteryByPrestige: Record<string, Record<string, number>>, detailedCount: number, };

export type StatsCommanderUnitRow = { created: number | string, made: number, lost: number | string, lost_percent: number | null, kills: number, KD: number | null, kill_percentage: number, };

export type StatsDifficultyDataRow = { Victory: number, Defeat: number, Winrate: number, };

export type StatsFastestMapDetails = { length: number, file: string, date: number, difficulty: string, players: Array<StatsFastestMapPlayer>, enemy_race: string, };

export type StatsFastestMapPlayer = { name: string, handle: string, commander: string, apm: number, mastery_level: number, masteries: Array<number>, prestige: number, prestige_name: string, };

export type StatsMapDataRow = { id: string, average_victory_time: number, frequency: number, Victory: number, Defeat: number, Winrate: number, bonus: number, detailedCount: number, Fastest: StatsFastestMapDetails, };

export type StatsPlayerDataRow = { wins: number, losses: number, winrate: number, kills: number, apm: number, frequency: number, last_seen: number, commander: string, };

export type StatsRegionDataRow = { frequency: number, Victory: number, Defeat: number, winrate: number, max_asc: number, prestiges: Record<string, number>, max_com: Array<string>, };

export type StatsStatePayload = { ready: boolean, games: number, detailed_parsed_count: number, total_valid_files: number, analysis?: StatsAnalysisPayload, main_players: Array<string>, main_handles: Array<string>, analysis_running: boolean, analysis_running_mode?: string, simple_analysis_status: string, detailed_analysis_status: string, detailed_analysis_atstart: boolean, prestige_names: { [key in string]: LocalizedLabels }, message: string, scan_progress: ReplayScanProgressPayload, query?: string, };

export type StatsUnitDataPayload = { main: Record<string, ({ count: number } & Record<string, StatsCommanderUnitRow | number>) | null>, ally: Record<string, ({ count: number } & Record<string, StatsCommanderUnitRow | number>) | null>, amon: { [key in string]: StatsAmonUnitRow }, };

export type UiMutatorRow = { id: string, name: LocalizedText, iconName: string, description: LocalizedText, };

export type WeeklyRowPayload = { mutation: string, nameEn: string, nameKo: string, map: string, mutators: Array<UiMutatorRow>, mutationOrder: number, isCurrent: boolean, nextDurationDays: number, nextDuration: string, difficulty: string, wins: number, losses: number, winrate: number, };
