// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AppSettings = { start_with_windows: boolean, minimize_to_tray: boolean, start_minimized: boolean, auto_update: boolean, duration: number, show_player_winrates: boolean, show_replay_info_after_game: boolean, show_session: boolean, show_charts: boolean, account_folder: string, screenshot_folder: string, color_player1: string, color_player2: string, color_amon: string, color_mastery: string, "hotkey_show/hide": string | null, hotkey_show: string | null, hotkey_hide: string | null, hotkey_newer: string | null, hotkey_older: string | null, hotkey_winrates: string | null, enable_logging: boolean, dark_theme: boolean, language: string, monitor: number, performance_show: boolean, performance_hotkey: string | null, performance_processes: Array<string>, performance_geometry?: [number, number, number, number], rng_choices: { [key in string]?: boolean }, player_notes: { [key in string]?: string }, main_names: Array<string>, detailed_analysis_atstart: boolean, };

export type EmptyPayload = Record<string, never>;

export type LocalizedLabels = { ko: Array<string>, en: Array<string>, };

export type MonitorOption = { index: number, label: string, };

export type OverlayColorPreviewPayload = { color_player1?: string, color_player2?: string, color_amon?: string, color_mastery?: string, };

export type OverlayIconValue = number | Array<string>;

export type OverlayInitColorsDurationPayload = { colors: [string | null, string | null, string | null, string | null], duration: number, show_charts: boolean, show_session: boolean, session_victory: number, session_defeat: number, language: string, };

export type OverlayLanguagePreviewPayload = { language: string, };

export type OverlayPlayerInfoPayload = { data: { [key in string]?: OverlayPlayerInfoRow }, };

export type OverlayPlayerInfoRow = { "kind": "no_games", note?: string, } | { "kind": "stats", wins: number, losses: number, apm: number, commander: string, frequency: number, kills: number, last_seen_relative: string, note?: string, };

export type OverlayRandomizerCatalog = { prestige_names: { [key in string]?: LocalizedLabels }, };

export type OverlayReplayPayload = { file: string, map_name: string, main: string, ally: string, mainCommander: string, allyCommander: string, mainAPM: number, allyAPM: number, mainkills: number, allykills: number, result: string, difficulty: string, length: number, "B+": number, weekly: boolean, weekly_name?: string, extension: boolean, mainCommanderLevel: number, allyCommanderLevel: number, mainMasteries: Array<number>, allyMasteries: Array<number>, mainUnits: { [key in string]?: [number, number, number, number] }, allyUnits: { [key in string]?: [number, number, number, number] }, amon_units: { [key in string]?: [number, number, number, number] }, mainIcons: { [key in string]?: OverlayIconValue }, allyIcons: { [key in string]?: OverlayIconValue }, mutators: Array<string>, bonus: Array<number>, bonus_total?: number, player_stats?: { [key in string]?: ReplayPlayerSeries }, mainPrestige: string, allyPrestige: string, Victory?: number, Defeat?: number, Commander?: string, Prestige?: string, newReplay?: boolean, fastest?: boolean, comp: string, };

export type OverlayScreenshotRequestPayload = { path: string, };

export type OverlayScreenshotResultPayload = { ok: boolean, path: string, message: string, };

export type PerformanceVisibilityPayload = { visible: boolean, };

export type RandomizerResult = { commander: string, prestige: bigint, mastery_indices: Array<bigint | null>, map_race: string, };

export type ReplayPlayerSeries = { name: string, army: Array<number>, supply: Array<number>, killed: Array<number>, mining: Array<number>, };
