use super::replay_event_handlers::{
    IdentifiedWavesMap, ReplayEventStringSets, ReplayMapAnalysisFlags, ReplayPlayerIdSet,
    TextListMapping, UnitBornOrInitEventFields, UnitDiedEventFields, UnitSnapshot, UnitStateMap,
    UnitTypeChangeEventFields, UnitTypeCountMap, WaveUnitsState,
};
use super::{ReplayAnalysisSets, ReplayDetailedEventCollection, ReplayMutatorParseContext};
use crate::dictionary_data::{UnitAddKillsToJson, UnitNamesJson};
use std::collections::{BTreeMap, HashMap, HashSet};

pub(super) type UnitStats = (i64, i64, i64, f64);

pub(super) struct ReplayMutatorIdentificationInput<'a> {
    pub(super) event_collection: Option<&'a ReplayDetailedEventCollection>,
    pub(super) mutators_all: &'a [String],
    pub(super) mutators_ui: &'a [String],
    pub(super) mutator_ids: &'a crate::dictionary_data::MutatorIdsJson,
    pub(super) cached_mutators: &'a crate::dictionary_data::CachedMutatorsJson,
    pub(super) extension: bool,
    pub(super) mm: bool,
    pub(super) mutator_context: Option<&'a ReplayMutatorParseContext>,
}

pub(super) struct FillUnitKillsAndIconsInput<'a> {
    pub(super) base_icons: &'a BTreeMap<String, u64>,
    pub(super) player: i64,
    pub(super) main_player: i64,
    pub(super) unit_counts: &'a UnitTypeCountMap,
    pub(super) ally_kills_counted_toward_main: i64,
    pub(super) killcounts: &'a [i64],
    pub(super) unit_name_dict: &'a UnitNamesJson,
    pub(super) unit_add_kills_to: &'a UnitAddKillsToJson,
    pub(super) unit_add_losses_to: &'a HashMap<String, String>,
    pub(super) analysis_sets: &'a ReplayAnalysisSets,
}

pub(super) struct UpgradeEventHandlerInput<'a> {
    pub(super) upg_name: &'a str,
    pub(super) upg_pid: i64,
    pub(super) upgrade_count: i64,
    pub(super) main_player: i64,
    pub(super) ally_player: i64,
    pub(super) commander_upgrades: &'a HashMap<String, String>,
    pub(super) mastery_upgrade_indices: &'a HashMap<String, i64>,
    pub(super) prestige_upgrade_names: &'a HashMap<String, String>,
}

pub(super) struct UnitBornOrInitHandlerInput<'event, 'unit> {
    pub(super) event: &'event UnitBornOrInitEventFields<'unit>,
    pub(super) main_player: i64,
    pub(super) ally_player: i64,
    pub(super) amon_players: &'event ReplayPlayerIdSet,
    pub(super) unit_dict: &'event mut UnitStateMap,
    pub(super) start_time: f64,
    pub(super) unit_type_dict_main: &'event mut UnitTypeCountMap,
    pub(super) unit_type_dict_ally: &'event mut UnitTypeCountMap,
    pub(super) unit_type_dict_amon: &'event mut UnitTypeCountMap,
    pub(super) mutator_dehaka_drag_unit_ids: &'event mut HashSet<i64>,
    pub(super) murvar_spawns: &'event mut HashSet<i64>,
    pub(super) glevig_spawns: &'event mut HashSet<i64>,
    pub(super) broodlord_broodlings: &'event mut HashSet<i64>,
    pub(super) outlaw_order: &'event mut Vec<String>,
    pub(super) outlaw_order_seen: &'event mut HashSet<String>,
    pub(super) wave_units: &'event mut WaveUnitsState,
    pub(super) identified_waves: &'event mut IdentifiedWavesMap,
    pub(super) abathur_kill_locusts: &'event mut HashSet<i64>,
    pub(super) last_biomass_position: [i64; 3],
    pub(super) revival_types: &'event HashMap<String, String>,
    pub(super) primal_combat_predecessors: &'event HashMap<String, String>,
    pub(super) tychus_outlaws: &'event HashSet<String>,
    pub(super) units_in_waves: &'event HashSet<String>,
    pub(super) string_sets: &'event ReplayEventStringSets,
}

pub(super) struct UnitTypeChangeHandlerInput<'event, 'unit> {
    pub(super) event: &'event UnitTypeChangeEventFields<'unit>,
    pub(super) map_flags: &'event ReplayMapAnalysisFlags,
    pub(super) main_player: i64,
    pub(super) ally_player: i64,
    pub(super) amon_players: &'event ReplayPlayerIdSet,
    pub(super) unit_dict: &'event mut UnitStateMap,
    pub(super) unit_type_dict_main: &'event mut UnitTypeCountMap,
    pub(super) unit_type_dict_ally: &'event mut UnitTypeCountMap,
    pub(super) unit_type_dict_amon: &'event mut UnitTypeCountMap,
    pub(super) start_time: f64,
    pub(super) bonus_timings: &'event mut Vec<f64>,
    pub(super) legacy_spawn_filter_unit_id: i64,
    pub(super) glevig_spawns: &'event HashSet<i64>,
    pub(super) murvar_spawns: &'event HashSet<i64>,
    pub(super) zagaras_dummy_zerglings: &'event mut HashSet<i64>,
    pub(super) broodlord_broodlings: &'event HashSet<i64>,
    pub(super) research_vessel_landed_timing: Option<i64>,
    pub(super) units_killed_in_morph: &'event HashSet<String>,
    pub(super) unit_name_dict: &'event UnitNamesJson,
    pub(super) unit_add_losses_to: &'event HashSet<String>,
    pub(super) dont_count_morphs: &'event HashSet<String>,
    pub(super) string_sets: &'event ReplayEventStringSets,
}

pub(super) struct UnitOwnerChangeHandlerInput<'a> {
    pub(super) event_unit_id: i64,
    pub(super) map_flags: &'a ReplayMapAnalysisFlags,
    pub(super) control_pid: i64,
    pub(super) main_player: i64,
    pub(super) ally_player: i64,
    pub(super) amon_players: &'a ReplayPlayerIdSet,
    pub(super) unit_dict: &'a mut UnitStateMap,
    pub(super) game_time: f64,
    pub(super) bonus_timings: &'a mut Vec<f64>,
    pub(super) mw_bonus_initial_timing: &'a mut [f64; 2],
}

pub(super) struct UnitDiedKillStatsHandlerInput<'a> {
    pub(super) killed_row: Option<&'a UnitSnapshot>,
    pub(super) killing_player: Option<i64>,
    pub(super) gameloop: i64,
    pub(super) main_player: i64,
    pub(super) ally_player: i64,
    pub(super) amon_players: &'a ReplayPlayerIdSet,
    pub(super) killcounts: &'a mut [i64],
    pub(super) ally_kills_transfer_to_main: bool,
    pub(super) last_aoe_unit_killed: &'a mut [Option<(String, f64)>],
    pub(super) ally_kills_counted_toward_main: i64,
    pub(super) do_not_count_kills: &'a HashSet<String>,
    pub(super) aoe_units: &'a HashSet<String>,
}

pub(super) struct UnitDiedDetailHandlerInput<'event, 'snapshot> {
    pub(super) event: &'event UnitDiedEventFields,
    pub(super) killed_row: &'snapshot UnitSnapshot,
    pub(super) map_flags: &'event ReplayMapAnalysisFlags,
    pub(super) main_player: i64,
    pub(super) ally_player: i64,
    pub(super) amon_players: &'event ReplayPlayerIdSet,
    pub(super) unit_id: i64,
    pub(super) unit_type_dict_main: &'event mut UnitTypeCountMap,
    pub(super) unit_type_dict_ally: &'event mut UnitTypeCountMap,
    pub(super) unit_type_dict_amon: &'event mut UnitTypeCountMap,
    pub(super) unit_dict: &'event UnitStateMap,
    pub(super) dt_ht_ignore: &'event mut [i64],
    pub(super) start_time: f64,
    pub(super) commander_by_player: &'event HashMap<i64, String>,
    pub(super) killbot_feed: &'event mut [i64],
    pub(super) custom_kill_count: &'event mut super::replay_event_handlers::NestedPlayerCountMap,
    pub(super) used_mutator_spider_mines: &'event mut HashSet<i64>,
    pub(super) bonus_timings: &'event mut Vec<f64>,
    pub(super) abathur_kill_locusts: &'event HashSet<i64>,
    pub(super) mutator_dehaka_drag_unit_ids: &'event HashSet<i64>,
    pub(super) murvar_spawns: &'event HashSet<i64>,
    pub(super) glevig_spawns: &'event HashSet<i64>,
    pub(super) broodlord_broodlings: &'event HashSet<i64>,
    pub(super) unit_killed_by: &'event mut TextListMapping,
    pub(super) mind_controlled_units: &'event HashSet<i64>,
    pub(super) zagaras_dummy_zerglings: &'event HashSet<i64>,
    pub(super) last_aoe_unit_killed: &'event [Option<(String, f64)>],
    pub(super) commander_no_units: &'event HashMap<String, Vec<String>>,
    pub(super) commander_no_units_values: &'event HashSet<String>,
    pub(super) hfts_units: &'event HashSet<String>,
    pub(super) tus_units: &'event HashSet<String>,
    pub(super) do_not_count_kills: &'event HashSet<String>,
    pub(super) self_killing_units: &'event HashSet<String>,
    pub(super) duplicating_units: &'event HashSet<String>,
    pub(super) salvage_units: &'event HashSet<String>,
    pub(super) string_sets: &'event ReplayEventStringSets,
}
